FROM php:8.1-fpm

# COPY php.ini
COPY ./php.ini /usr/local/etc/php/php.ini

# Composer install
COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

# install Node.js
COPY --from=node:lts /usr/local/bin /usr/local/bin
COPY --from=node:lts /usr/local/lib /usr/local/lib

RUN apt-get update && \
    apt-get -y install \
    git \
    zip \
    unzip \
    vim \
    libcurl4-openssl-dev \
    pkg-config \
    libssl-dev\
    && docker-php-ext-install pdo_mysql bcmath \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb

EXPOSE 5173
EXPOSE 3000
WORKDIR /var/www/html