version: '3.3'

volumes:
  mongo-data:

services:
  app:
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - ${VITE_PORT}:5173
      - ${SOCKET_PORT}:3000
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=${DB_HOST}
      - DB_PORT=${MONGO_PORT}
      - DB_DATABASE=${MONGO_EXPRESS_USER}
      - DB_USERNAME=${MONGO_EXPRESS_USER}
      - DB_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - "TZ=Asia/Tokyo"
    
  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:80

    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html
  mongo:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    build:
      context: ./docker/mongo-express
      dockerfile: Dockerfile
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_EXPRESS_SERVER}
    depends_on:
      - mongo
  redis:
    build: 
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  laravel-echo-server:
    build: 
      context: ./docker/laravel-echo-server
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /work
    ports:
      - 6001:6001
      - 6002:6002
    # build:
    #   context: ./docker/mysql
    #   dockerfile: Dockerfile
    # ports:
    #   - ${DB_PORT}:3306
    # environment:
    #   MYSQL_DATABASE: ${DB_NAME}
    #   MYSQL_USER: ${DB_USER}
    #   MYSQL_PASSWORD: ${DB_PASSWORD}
    #   MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #   TZ: 'Asia/Tokyo'
    # volumes:
    #   - mysql-volume:/var/lib/mysql